const variables = {
  bgPrimary: "var(--bg-primary)",
  bgSecondary: "var(--bg-secondary)",
  bgGlass: "var(--bg-glass)",
  bgGlassHover: "var(--bg-glass-hover)",
  borderGlass: "var(--border-glass)",
  bgCard: "var(--bg-card)",
  purplePrimary: "#8b5cf6",
  purpleLight: "#a855f7",
  purpleGlow: "var(--purple-glow)",
  purpleGlowStrong: "var(--purple-glow-strong)",
  textPrimary: "var(--text-primary)",
  textSecondary: "var(--text-secondary)",
  textMuted: "var(--text-muted)",
  accentBlue: "#3b82f6",
  accentPink: "#ec4899",
  radiusSm: "8px",
  radiusMd: "12px",
  radiusLg: "16px",
  radiusXl: "24px",
  maxWidth: "1200px",
  navHeight: "72px",
  transition: "0.3s cubic-bezier(0.4, 0, 0.2, 1)",
  fontFamily: "'Inter', sans-serif",
};

export default variables;
